# netlify.toml

# 1. Build command and publish directory
[build]
  command = "npm run build"
  publish = ".next"

# 2. Next.js plugin declaration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 3. Function configuration (FIXED SYNTAX)
# This sets the timeout for ALL serverless functions in the project.
# Since only the audit function is long-running, this is safe.
[functions]
  timeout = 60 # Increase default timeout to 60 seconds

# 4. Keep your existing headers
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"