# netlify.toml

# 1. Build command and publish directory
[build]
  command = "npm run build"
  publish = ".next"

# 2. Next.js plugin declaration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 3. Global function configuration (FIXED SYNTAX - Simpler)
# Use single brackets to set defaults for ALL functions
[functions]
  timeout = 60 # Increase default timeout for ALL functions to 60 seconds

# 4. Keep your existing headers
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"