# netlify.toml

# 1. Build command and publish directory
[build]
  command = "npm run build"
  publish = ".next"

# 2. Next.js plugin declaration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 3. Target the specific audit function by likely generated name (FINAL ATTEMPT)
[functions."app/api/audit/route"] # Use the file path as the function identifier
  timeout = 60 # Increase timeout just for this function to 60 seconds

# 4. Keep your existing headers
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"